dist: trusty
sudo: required
language: java
addons:
  - postgresql: "9.4"
os:
    - linux
notifications:
  webhooks:
    urls:
      - http://52.10.123.209:8085/travishook
    on_success: always
    on_failure: always
    on_start: never
script:
    - tools/ci/build.sh
    - tools/ci/test.sh
